version: '3'

services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:8080

  frontend:
    image: php:apache
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - backend