version: '3'

services:

  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    links:
      - products-service

  products-service:
    build: ./backend
    deploy:
      resources:
        limits:
        # percentage of cpu
          cpus: '0.5' 
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 9000:8080
